## Numpy

Numpy is a library which provides support for large, homogeneous mulit-dimensional arrays and matrices

In [3]:
# import numpy
import numpy as np

## Creating Arrays in Numpy

### Creating an array from a list

In [27]:
list1 = [10,20,30]
list1

[10, 20, 30]

In [28]:
arr1 = np.array(list1)
arr1

array([10, 20, 30])

In [29]:
type(arr1)

numpy.ndarray

### Using arrange to create an array

the difference between array and arrange is that array takes in a list and turns it into an array, whereas arrange creates from a range of numbers

In [30]:
arr2 = np.arange(10,20, 1) # (Start,Stop,Step-size)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

## Multidimensional arrays

### Combining two list - Two-dimensional arrays

When we combine arrays together, we can add dimension. Combining two arrays gives us a 2D array
This creates a matrix for us on which we can perform matrix opperations

In [31]:
# combining 2 lists
list2 = [40,50,60]

list3 = [list1,list2]

arr3 = np.array(list3)
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [32]:
arr3.shape

(2, 3)

## Three-dimensional arrays

In [33]:
arr3dim = np.array([[[1,2,3],[3,4,5]],[[5,6,7],[8,9,10]]])
arr3dim

array([[[ 1,  2,  3],
        [ 3,  4,  5]],

       [[ 5,  6,  7],
        [ 8,  9, 10]]])

In [34]:
arr3dim.shape

(2, 2, 3)

## Using Arrays and Scalars

Numpy arrays (or ndarray) allow us to perform matrix operations.

In [35]:
# For example, we can use simple multiplication

arr3dim * 3

array([[[ 3,  6,  9],
        [ 9, 12, 15]],

       [[15, 18, 21],
        [24, 27, 30]]])

In [36]:
list1 * 3

[10, 20, 30, 10, 20, 30, 10, 20, 30]

### We can multiply arrays by other arrays 

In [37]:
arr11 = np.array(list2)
arr1 * arr11 

array([ 400, 1000, 1800])

### multiplying by arrays of different shapes

In [38]:
arr1 * arr2

ValueError: operands could not be broadcast together with shapes (3,) (10,) 

### miltiplication can be done by arrays of different dimensions but they need the same element size

In [39]:
arr1 * arr3dim

array([[[ 10,  40,  90],
        [ 30,  80, 150]],

       [[ 50, 120, 210],
        [ 80, 180, 300]]])

### One dimensional array with 12 elements (12,)

In [41]:
arr12 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr12.shape

(12,)

### Two dimensional array size (3, 4)

In [47]:
list1 = [1,2,3,4]
list2 = [list1,list1,list1]
arr3_4 = np.array(list2)
arr3_4.shape

(3, 4)

### Three dimensional array size (2, 5, 4)

In [48]:
list1 = [1,2,3,4]
list2 = [list1,list1,list1,list1,list1]
list3 = [list2,list2]
arr2_5_4 = np.array(list3)
arr2_5_4.shape

(2, 5, 4)

In [49]:
arr2_5_4

array([[[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]]])

### Accessing the values in ndarrays

In [50]:
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [53]:
arr3[1][2]

60

In [54]:
arr3[1,2]

60

In [55]:
arr3[1]

array([40, 50, 60])

In [58]:
arr3[:,2]

array([30, 60])

## Statistical functions and arrays

In [59]:
# sum of values
arr3.sum()

210

In [60]:
# sum of all columns
arr3.sum(0)

array([50, 70, 90])

In [61]:
# sum of rows
arr3.sum(1)

array([ 60, 150])

In [62]:
# mean
arr3.mean()

35.0

In [66]:
#mean of column
arr3.mean(0)

array([25., 35., 45.])

In [65]:
# standard deviation
arr3.std()

17.07825127659933

In [67]:
# variance
arr3.var()


291.6666666666667

In [68]:
#max
arr3.max()

60

In [69]:
#min
arr3.min()

10

## Iterating through ndarrays

In [70]:
for x in arr1:
    print(x)

10
20
30


In [73]:
for x in arr3:
    for y in x:
        print(y)

10
20
30
40
50
60


In [76]:
for x in arr2_5_4:
    for y in x:
        for z in x:
            print(z)

[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]


In [77]:
for x in np.nditer(arr3):
    print(x)

10
20
30
40
50
60


In [78]:
for x in np.nditer(arr2_5_4):
    print(x)

1
2
3
4
1
2
3
4
1
2
3
4
1
2
3
4
1
2
3
4
1
2
3
4
1
2
3
4
1
2
3
4
1
2
3
4
1
2
3
4


## Savinmg and Loading in numpy

In [79]:
np.save("new",arr3)

In [83]:
np.load("new.npy")

array([[10, 20, 30],
       [40, 50, 60]])

In [85]:
np.savetxt("new.txt",arr3, delimiter= ",")

In [86]:
np.loadtxt("new.txt",delimiter = ",")

array([[10., 20., 30.],
       [40., 50., 60.]])