## Numpy

Numpy is a library which provides support for large, homogeneous mulit-dimensional arrays and matrices

In [3]:
# import numpy
import numpy as np

## Creating Arrays in Numpy

### Creating an array from a list

In [4]:
list1 = [10,20,30,40]
list1

[10, 20, 30, 40]

In [6]:
arr1 = np.array(list1)
arr1

array([10, 20, 30, 40])

In [7]:
type(arr1)

numpy.ndarray

### Using arrange to create an array

the difference between array and arrange is that array takes in a list and turns it into an array, whereas arrange creates from a range of numbers

In [10]:
arr2 = np.arange(10,20, 1) # (Start,Stop,Step-size)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

## Multidimensional arrays

### Combining two list - Two-dimensional arrays

When we combine arrays together, we can add dimension. Combining two arrays gives us a 2D array
This creates a matrix for us on which we can perform matrix opperations

In [14]:
# combining 2 lists
list2 = [40,50,60,70]

list3 = [list1,list2]

arr3 = np.array(list3)
arr3

array([[10, 20, 30, 40],
       [40, 50, 60, 70]])

In [15]:
arr3.shape

(2, 4)

## Three-dimensional arrays